on: [push, pull_request]
name: tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x, 1.20.x, 1.21.x, 1.22.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2
      - name: Test
        run: go test ./... -count=100
